services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0 
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      # envirement varaibles for expo go
      KC_PROXY_HEADERS: xforwarded
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
    expose:
      - "8080"
    volumes:
      - ./infrastructure/realm-export.json:/opt/keycloak/data/import/realm.json:ro
      - keycloak_data:/opt/keycloak/data
    networks:
      - frontend-net
      - backend-net

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./infrastructure/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - keycloak
      - admin
    networks:
      - frontend-net
      
  backend:
    build:
      context: ./backend/
    environment:
      DB_USER: $DB_USER
      DB_NAME: $DB_NAME
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
    expose:
      - "5000"
    develop:
      watch:
      - action: sync+restart
        path: ./backend
        target: /app/
        ignore:
            - .venv/
            - venv/
            - __pycache__/
            - "*.pyc"
      - action: rebuild
        path: ./backend/requirements.txt
    networks:
      - frontend-net
      - backend-net

  admin:
    build:
      context: ./admin/
    expose:
      - "3000"
    develop:
      watch:
      - action: sync
        path: ./admin
        target: /app/
        ignore:
            - node_modules/
            - .next/
      - action: rebuild
        path: ./admin/package.json
    networks:
      - frontend-net

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s
    networks:
      - backend-net
    secrets:
      - db_password

volumes:
  postgres_data:
  keycloak_data:

secrets:
  db_password:
    file: infrastructure/secrets/db_password.txt

networks:
  frontend-net:
    driver: bridge
  backend-net:
    driver: bridge