"""modyfing task table

Revision ID: 6e1cc0aa1da5
Revises: c1352326afee
Create Date: 2026-09-07 11:48:52.284161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e1cc0aa1da5'
down_revision = 'c1352326afee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(), nullable=False, server_default='single_choice'))
        batch_op.add_column(sa.Column('order_index', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('content_key', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('accepted_answers', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('memory_pairs', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('themes', sa.JSON(), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('difficulty_level',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_unique_constraint(None, ['content_key'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('difficulty_level',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('themes')
        batch_op.drop_column('memory_pairs')
        batch_op.drop_column('accepted_answers')
        batch_op.drop_column('content_key')
        batch_op.drop_column('order_index')
        batch_op.drop_column('type')

    # ### end Alembic commands ###
