"""drop theme and variant_group from tasks

Revision ID: 77614042c813
Revises: febedd819cd4
Create Date: 2026-08-23 21:10:08.829690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77614042c813'
down_revision = 'febedd819cd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('theme')
        batch_op.drop_column('variant_group')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('variant_group', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('theme', sa.TEXT(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
