"""add teacher fields to users

Revision ID: f770bb7b00a5
Revises: 5eec15b4a89e
Create Date: 2026-08-25 11:54:03.785190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f770bb7b00a5'
down_revision = '5eec15b4a89e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('teacher_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_teacher_id'), ['teacher_id'], unique=False)
        batch_op.create_foreign_key('users_teacher_id_fkey', 'users', ['teacher_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_teacher_id_fkey', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_column('teacher_id')
        batch_op.drop_column('email')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
