"""creating ebooks table

Revision ID: ff3d1d2734b4
Revises: 6e1cc0aa1da5
Create Date: 2026-09-14 13:42:24.504098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff3d1d2734b4'
down_revision = '6e1cc0aa1da5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ebooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subsection_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('intro', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subsection_id'], ['subsections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ebooks')
    # ### end Alembic commands ###
